package Juego;

import Juego.Tablero;
import java.awt.Color;
import javax.swing.JColorChooser;

public class IUOpciones extends javax.swing.JDialog {

    /** Creates new form IUOpciones */
    Tablero tablero;

    public IUOpciones(java.awt.Frame parent, boolean modal, Tablero tbl) {
        super(parent, modal);
        tablero = tbl;
        initComponents();
        cmbBlancas.setSelectedIndex(1);
        cmbNegras.setSelectedIndex(1);
        if (tablero.getTurnoComputadora() == 1) {
            cmbBlancas.setSelectedIndex(0);
        } else {
            if (tablero.getTurnoComputadora() == -1) {
                cmbNegras.setSelectedIndex(0);
            }
        }
        chbxMostrarAlternetivas.setSelected(tablero.isSeleccionarAlternativas());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cmbNegras = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnDefault = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cmbBlancas = new javax.swing.JComboBox();
        chbxMostrarAlternetivas = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlBlanco = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnlBlancoResaltado = new javax.swing.JPanel();
        pnlNegroResaltado = new javax.swing.JPanel();
        lbllSeleccionado = new javax.swing.JLabel();
        lblAlerta = new javax.swing.JLabel();
        pnlAlerta = new javax.swing.JPanel();
        pnlSeleccionado = new javax.swing.JPanel();
        pnlNegro = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuracion y Preferencias");
        setResizable(false);

        cmbNegras.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Computadora", "Humano" }));
        cmbNegras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNegrasActionPerformed(evt);
            }
        });

        jLabel1.setText("Negras:");

        jLabel2.setText("Blancas:");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnDefault.setText("Por Defecto");
        btnDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefaultActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        cmbBlancas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Computadora", "Humano" }));
        cmbBlancas.setSelectedIndex(1);
        cmbBlancas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBlancasActionPerformed(evt);
            }
        });

        chbxMostrarAlternetivas.setText("Mostrar Alternativas de Movimiento");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuracion de Colores de Casillas"));

        jLabel3.setText("Casilla Blanca:");

        jLabel4.setText("Casilla Negra:");

        pnlBlanco.setBackground(tablero.getBlanco());
        pnlBlanco.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlBlanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBlancoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlBlancoLayout = new javax.swing.GroupLayout(pnlBlanco);
        pnlBlanco.setLayout(pnlBlancoLayout);
        pnlBlancoLayout.setHorizontalGroup(
            pnlBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        pnlBlancoLayout.setVerticalGroup(
            pnlBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel5.setText("Casilla Blanca Resaltada:");

        jLabel6.setText("Casilla Negra Resaltada:");

        pnlBlancoResaltado.setBackground(tablero.getBlancoResaltado());
        pnlBlancoResaltado.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlBlancoResaltado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBlancoResaltadoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlBlancoResaltadoLayout = new javax.swing.GroupLayout(pnlBlancoResaltado);
        pnlBlancoResaltado.setLayout(pnlBlancoResaltadoLayout);
        pnlBlancoResaltadoLayout.setHorizontalGroup(
            pnlBlancoResaltadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        pnlBlancoResaltadoLayout.setVerticalGroup(
            pnlBlancoResaltadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlNegroResaltado.setBackground(tablero.getNegroResaltado());
        pnlNegroResaltado.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlNegroResaltado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlNegroResaltadoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlNegroResaltadoLayout = new javax.swing.GroupLayout(pnlNegroResaltado);
        pnlNegroResaltado.setLayout(pnlNegroResaltadoLayout);
        pnlNegroResaltadoLayout.setHorizontalGroup(
            pnlNegroResaltadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        pnlNegroResaltadoLayout.setVerticalGroup(
            pnlNegroResaltadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lbllSeleccionado.setText("Casilla Seleccionada:");

        lblAlerta.setText("Alerta Casilla:");

        pnlAlerta.setBackground(tablero.getAlerta());
        pnlAlerta.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlAlerta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAlertaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlAlertaLayout = new javax.swing.GroupLayout(pnlAlerta);
        pnlAlerta.setLayout(pnlAlertaLayout);
        pnlAlertaLayout.setHorizontalGroup(
            pnlAlertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        pnlAlertaLayout.setVerticalGroup(
            pnlAlertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlSeleccionado.setBackground(tablero.getSeleccionado());
        pnlSeleccionado.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlSeleccionado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSeleccionadoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlSeleccionadoLayout = new javax.swing.GroupLayout(pnlSeleccionado);
        pnlSeleccionado.setLayout(pnlSeleccionadoLayout);
        pnlSeleccionadoLayout.setHorizontalGroup(
            pnlSeleccionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        pnlSeleccionadoLayout.setVerticalGroup(
            pnlSeleccionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlNegro.setBackground(tablero.getNegro());
        pnlNegro.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlNegro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlNegroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlNegroLayout = new javax.swing.GroupLayout(pnlNegro);
        pnlNegro.setLayout(pnlNegroLayout);
        pnlNegroLayout.setHorizontalGroup(
            pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        pnlNegroLayout.setVerticalGroup(
            pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel7.setText("Juego creado por: Villalobos Contreras Jesus");

        jLabel8.setText("Alcalá Rangel Jeffrey Alexander");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbllSeleccionado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pnlNegro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlNegroResaltado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pnlBlancoResaltado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAlerta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pnlAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAlerta))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pnlAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlBlanco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pnlNegroResaltado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addComponent(jLabel4))
                            .addComponent(pnlNegro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(pnlBlancoResaltado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbllSeleccionado)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(chbxMostrarAlternetivas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cmbBlancas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbNegras, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDefault, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAceptar, btnCancelar, btnDefault});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbBlancas, cmbNegras});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnAceptar)
                    .addComponent(cmbNegras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnDefault)
                    .addComponent(cmbBlancas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(chbxMostrarAlternetivas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefaultActionPerformed
        cmbNegras.setSelectedIndex(0);                // TODO add your handling code here:
        cmbBlancas.setSelectedIndex(1);
        chbxMostrarAlternetivas.setSelected(true);

        pnlNegro.setBackground(Color.darkGray);
        pnlNegroResaltado.setBackground(new Color(120, pnlNegro.getBackground().getGreen() - 64, pnlNegro.getBackground().getBlue() - 64, 100));
        pnlBlanco.setBackground(Color.white);
        pnlBlancoResaltado.setBackground(new Color(120, pnlBlanco.getBackground().getGreen() - 64, pnlBlanco.getBackground().getBlue() - 64, 100));
        pnlSeleccionado.setBackground(Color.LIGHT_GRAY);
        pnlAlerta.setBackground(Color.RED);

    }//GEN-LAST:event_btnDefaultActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (cmbBlancas.getSelectedIndex() == 0) {
            tablero.setTurnoComputadora(1);// TODO add your handling code here:
        } else if (cmbNegras.getSelectedIndex() == 0) {
            tablero.setTurnoComputadora(-1);// TODO add your handling code here:
        } else {
            tablero.setTurnoComputadora(0);
        }
        tablero.setSeleccionarAlternativas(chbxMostrarAlternetivas.isSelected());
        tablero.setNegro(pnlNegro.getBackground());
        tablero.setNegroResaltado(pnlNegroResaltado.getBackground());
        tablero.setBlanco(pnlBlanco.getBackground());
        tablero.setBlancoResaltado(pnlBlancoResaltado.getBackground());
        tablero.setSeleccionado(pnlSeleccionado.getBackground());
        tablero.setAlerta(pnlAlerta.getBackground());
        tablero.ordenarTablero();
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void cmbNegrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNegrasActionPerformed
        if (cmbNegras.getSelectedIndex() == 0) {
            cmbBlancas.setSelectedIndex(1);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNegrasActionPerformed

    private void cmbBlancasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBlancasActionPerformed
        if (cmbBlancas.getSelectedIndex() == 0) {
            cmbNegras.setSelectedIndex(1);
        }
    }//GEN-LAST:event_cmbBlancasActionPerformed

    private void pnlBlancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBlancoMouseClicked
        pnlBlanco.setBackground(JColorChooser.showDialog(this, "Elegir Color", pnlBlanco.getBackground()));
}//GEN-LAST:event_pnlBlancoMouseClicked

    private void pnlBlancoResaltadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBlancoResaltadoMouseClicked
        pnlBlancoResaltado.setBackground(JColorChooser.showDialog(this, "Elegir Color", pnlBlancoResaltado.getBackground()));
    }//GEN-LAST:event_pnlBlancoResaltadoMouseClicked

    private void pnlNegroResaltadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNegroResaltadoMouseClicked
        pnlNegroResaltado.setBackground(JColorChooser.showDialog(this, "Elegir Color", pnlNegroResaltado.getBackground()));
    }//GEN-LAST:event_pnlNegroResaltadoMouseClicked

    private void pnlSeleccionadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSeleccionadoMouseClicked
        pnlSeleccionado.setBackground(JColorChooser.showDialog(this, "Elegir Color", pnlSeleccionado.getBackground()));
    }//GEN-LAST:event_pnlSeleccionadoMouseClicked

    private void pnlAlertaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAlertaMouseClicked
        pnlAlerta.setBackground(JColorChooser.showDialog(this, "Elegir Color", pnlAlerta.getBackground()));
    }//GEN-LAST:event_pnlAlertaMouseClicked

    private void pnlNegroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNegroMouseClicked
        pnlNegro.setBackground(JColorChooser.showDialog(this, "Elegir Color", pnlNegro.getBackground()));
}//GEN-LAST:event_pnlNegroMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDefault;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chbxMostrarAlternetivas;
    private javax.swing.JComboBox cmbBlancas;
    private javax.swing.JComboBox cmbNegras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAlerta;
    private javax.swing.JLabel lbllSeleccionado;
    private javax.swing.JPanel pnlAlerta;
    private javax.swing.JPanel pnlBlanco;
    private javax.swing.JPanel pnlBlancoResaltado;
    private javax.swing.JPanel pnlNegro;
    private javax.swing.JPanel pnlNegroResaltado;
    private javax.swing.JPanel pnlSeleccionado;
    // End of variables declaration//GEN-END:variables
}
