-- MySQL Script generated by MySQL Workbench
-- Sat Jan  2 18:57:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema buscaminas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema buscaminas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `buscaminas` DEFAULT CHARACTER SET utf8 ;
USE `buscaminas` ;

-- -----------------------------------------------------
-- Table `buscaminas`.`jugadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buscaminas`.`jugadores` (
  `idjugadores` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `puntuacion` INT NOT NULL,
  PRIMARY KEY (`idjugadores`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
